'use strict';

const UI = {
  'file': document.getElementById('file'),
  'fileButton': document.getElementById('fileButton'),
  'fileContent': document.getElementById('fileContent'),
  'new': document.getElementById('new'),
  'export': document.getElementById('export'),
  'render': document.getElementById('render'),
  'edit': document.getElementById('edit'),
  'editButton': document.getElementById('editButton'),
  'editContent': document.getElementById('editContent'),
  'undo': document.getElementById('undo'),
  'redo': document.getElementById('redo'),
  'copy': document.getElementById('copy'),
  'paste': document.getElementById('paste'),
  'delete': document.getElementById('delete'),
  'add': document.getElementById('add'),
  'addButton': document.getElementById('addButton'),
  'addContent': document.getElementById('addContent'),
  'addObject': document.getElementById('addObject'),
  'capsule': document.getElementById('capsule'),
  'cone': document.getElementById('cone'),
  'cube': document.getElementById('cube'),
  'cylinder': document.getElementById('cylinder'),
  'knot': document.getElementById('knot'),
  'sphere': document.getElementById('sphere'),
  'torus': document.getElementById('torus'),
  'addLight': document.getElementById('addLight'),
  'point': document.getElementById('point'),
  'spot': document.getElementById('spot'),
  'help': document.getElementById('help'),
  'helpButton': document.getElementById('helpButton'),
  'helpContent': document.getElementById('helpContent'),
  'github': document.getElementById('github'),
  'hotkeysButton': document.getElementById('hotkeysButton'),
  'settings': document.getElementById('settings'),
  'settingsButton': document.getElementById('settingsButton'),
  'settingsContent': document.getElementById('settingsContent'),
  'settingsObjects': document.getElementById('settingsContent'),
  'sceneObjects': document.getElementById('sceneObjects'),
  'scene': document.getElementById('scene'),
  'camera': document.getElementById('camera'),
  'position': {
    'x': document.getElementById('positionX'),
    'y': document.getElementById('positionY'),
    'z': document.getElementById('positionZ')
  },
  'rotation': {
    'x': document.getElementById('rotationX'),
    'y': document.getElementById('rotationY'),
    'z': document.getElementById('rotationZ')
  },
  'scale': {
    'x': document.getElementById('scaleX'),
    'y': document.getElementById('scaleY'),
    'z': document.getElementById('scaleZ')
  },
  'material': document.getElementById('material'),
  'basic': document.getElementById('basic'),
  'lambert': document.getElementById('lambert'),
  'normal': document.getElementById('normal'),
  'phong': document.getElementById('phong'),
  'standard': document.getElementById('standard'),
  'properties': document.getElementById('properties'),
  'angle': document.getElementById('angle'),
  'background': document.getElementById('background'),
  'color': document.getElementById('color'),
  'fog': {
    'checkbox': document.getElementById('fogCheckbox'),
    'color': document.getElementById('fogColor')
  },
  'fov': document.getElementById('fov'),
  'intensity': document.getElementById('intensity'),
  'metalness': document.getElementById('metalness'),
  'opacity': document.getElementById('opacity'),
  'penumbra': document.getElementById('penumbra'),
  'roughness': document.getElementById('roughness'),
  'shininess': document.getElementById('shininess'),
  'transparent': document.getElementById('transparent'),
  'zoom': document.getElementById('zoom'),
  'viewHelper': document.getElementById('viewHelper'),
  'container': document.getElementById('container'),
  'hotkeys': document.getElementById('hotkeys')
};

export default UI;
